services:
  rag_ai_agent_db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - rag_ai_agent_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi-backend:
    build: .
    depends_on:
      rag_ai_agent_db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      PYTHONPATH: /app
      SERVICE_HOST: "0.0.0.0"
      SERVICE_PORT: 8080
      DEV: "true"
      # GROQ Configuration
      GROQ_API_KEY: ${GROQ_API_KEY}
      # LangSmith Configuration
      LANGSMITH_TRACING: ${LANGSMITH_TRACING}
      LANGSMITH_PROJECT: ${LANGSMITH_PROJECT}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      # PostgreSQL Configuration
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: rag_ai_agent_db  # use service name defined in docker-compose.yml
      POSTGRES_PORT: 5432 # use port defined in rag_ai_agent_db service of docker-compose.yml
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_APPLICATION_NAME: ${POSTGRES_APPLICATION_NAME}
      POSTGRES_MIN_CONNECTIONS_PER_POOL: ${POSTGRES_MIN_CONNECTIONS_PER_POOL}
      POSTGRES_MAX_CONNECTIONS_PER_POOL: ${POSTGRES_MAX_CONNECTIONS_PER_POOL}
    ports:
      - "8080:8080"
    command:
      [
        "uv",
        "run",
        "python",
        "-m",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
        "--reload",
      ]

volumes:
  rag_ai_agent_pgdata:
